### ISSUE TITLE
`expo-random` deprecated

### ISSUE THREAD

**Issue by SimenB** [LinusU/react-native-get-random-values#41]
See https://blog.expo.dev/expo-sdk-48-ccb8302e231

>`expo-random` merged into `expo-crypto`. `expo-crypto` now supports `getRandomValues`, `randomUUID` (UUID v4), and `digest` functions, which are compliant with the Web Crypto API equivalents. With this change,`expo-random` has become redundant and is now deprecated.

**Comment by MortadhaFadhlaoui** [comment]
### Quick patch `react-native-get-random-values+1.8.0.patch
`
```
diff --git a/node_modules/react-native-get-random-values/index.js b/node_modules/react-native-get-random-values/index.js
index 7b5e313..3dd4ea9 100644
--- a/node_modules/react-native-get-random-values/index.js
+++ b/node_modules/react-native-get-random-values/index.js
@@ -30,8 +30,15 @@ function getRandomBase64 (byteLength) {
     // Expo SDK 41-44
     return NativeModules.ExpoRandom.getRandomBase64String(byteLength)
   } else if (global.ExpoModules) {
-    // Expo SDK 45+
-    return global.ExpoModules.ExpoRandom.getRandomBase64String(byteLength);
+      if(global.ExpoModules.ExpoRandom){
+      // Expo SDK 45+
+      return global.ExpoModules.ExpoRandom.getRandomBase64String(byteLength);
+      } else if (global.ExpoModules.ExpoCrypto && global.ExpoModules.ExpoCrypto.getRandomBase64String){
+      // Expo SDK 48+
+        return global.ExpoModules.ExpoCrypto.getRandomBase64String(byteLength)
+      } else {
+        throw new Error('Native module not found')
+      }
   } else {
     throw new Error('Native module not found')
   }

```

**Comment by pvinis** [comment]
indeed. i see that there are private kotlin and swift functions. cool! ill try it now.

**Comment by LinusU** [comment]
Fixed in [🚢 1.9.0 / 2023-05-18](https://github.com/LinusU/react-native-get-random-values/releases/tag/v1.9.0)

**Comment by TobyEalden** [comment]
I'm still getting this error because ExpoRandom is still being accessed here: https://github.com/LinusU/react-native-get-random-values/blob/master/index.js#L34.

Running with 1.9.0 on Android via Expo on SDK 48.0.0 

![Screenshot_20230612-112445](https://github.com/LinusU/react-native-get-random-values/assets/1628365/ba77076f-b8fd-4131-be5a-42536fc0fbb4)

**Comment by LinusU** [comment]
@TobyEalden could you try running the following code directly in your application?

```js
global.expo.modules.ExpoCrypto.getRandomValues(array)
```

If it doesn't work, it's probably some setup problem with Expo. There is some discussion around this here: https://github.com/expo/expo/issues/17270

**Comment by TobyEalden** [comment]
@LinusU thanks for the response.

It looks like `global.expo.modules.ExpoCrypto.getRandomValues` is undefined in my application. Weird since it's a new (up-to-date) installation of Expo.

I'll look into the Expo issue you mentioned.

**Comment by davidwinograd1** [comment]
@lennertcl facing same issue. any fixes?
